#!/usr/bin/env bash
# Generate a `.env` file from each sibling andy-* service's
# `config/registration.json` so docker-compose port references stop
# being hardcoded in N different files.
#
# Each registration.json declares the canonical ports for one service
# (dotnetHttps, dockerHttps, dotnetPostgres, dockerPostgres, ...).
# This script enumerates every sibling manifest, flattens its ports
# into environment variables of the form:
#
#     ANDY_<SERVICE>_<PORT_KIND>=<port>      # camelCase -> SNAKE_CASE
#
#     ANDY_SETTINGS_DOCKER_HTTPS=7300
#     ANDY_SETTINGS_DOTNET_HTTPS=5300
#     ANDY_CONTAINERS_DOCKER_HTTPS=7200
#     ...
#
# The canonical file lands at:
#   andy-settings/dist/docker-ports.env
#
# Each consumer's docker-compose.yml references these via
# `${VAR:-<fallback>}` substitution; the fallback is the same port
# from the manifest, so `docker compose up` works even without the
# generator having been run (the env file exists only to keep all
# N composes in sync when ports change, centrally).
#
# Usage:
#   bash scripts/generate-docker-ports-env.sh
#
# Re-run whenever any sibling registration.json's `service.ports` block
# changes. Output is not committed (andy-settings/dist/ is gitignored).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MONOREPO_ROOT="$(cd "$REPO_ROOT/.." && pwd)"
OUT_DIR="$REPO_ROOT/dist"
OUT_FILE="$OUT_DIR/docker-ports.env"

mkdir -p "$OUT_DIR"

{
  echo "# Generated by scripts/generate-docker-ports-env.sh"
  echo "# Source: $MONOREPO_ROOT/andy-*/config/registration.json"
  echo "# Do not edit — re-run the generator to refresh."
  echo "# Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
} > "$OUT_FILE"

shopt -s nullglob
manifests=("$MONOREPO_ROOT"/andy-*/config/registration.json)
if (( ${#manifests[@]} == 0 )); then
  echo "error: no registration.json files found under $MONOREPO_ROOT/andy-*" >&2
  exit 1
fi

count=0
for manifest in "${manifests[@]}"; do
  python3 - "$manifest" <<'PY' >> "$OUT_FILE"
import json, re, sys

manifest_path = sys.argv[1]
with open(manifest_path) as f:
    m = json.load(f)

svc = m.get("service", {}) or {}
name = svc.get("name", "")
if not name:
    sys.exit(0)

env_prefix = name.upper().replace("-", "_")
ports = svc.get("ports") or {}
if not ports:
    sys.exit(0)

print(f"# --- {name} ---")
for k, v in ports.items():
    # camelCase -> SNAKE_CASE for readability: dockerHttps -> DOCKER_HTTPS
    env_key = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", k).upper()
    print(f"{env_prefix}_{env_key}={v}")
print()
PY
  count=$((count + 1))
done

echo "==> wrote $OUT_FILE ($count manifest(s))"
echo
echo "Consume from a docker-compose.yml via \${VAR:-<fallback>} substitution."
echo "Load explicitly with:"
echo "  docker compose --env-file $OUT_FILE up"
echo "or let docker compose auto-load a \`.env\` next to your compose file by"
echo "copying / symlinking it:"
echo "  cp $OUT_FILE .env           # per-repo, gitignored"
